### ISSUE TITLE
学长好，我想咨询一下这门课怎么样？

### ISSUE THREAD

**Issue by ChangQingAAS** [lblaoke/TJU-deeplearning2020#1]

**Comment by lblaoke** [comment]
你好，加一下我微信吧（ID：lblaoke）




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Jul 1, 2021
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[lblaoke/TJU-deeplearning2020] 学长好，我想咨询一下这门课怎么样？ (#1)





 
额，下学期可以选一些专业选修，不知道哪些比较好。想咨询一下学长的建议QAQ。
 求求你了，帮帮可莉吧
 
 谢谢学长 嘤嘤嘤嘤嘤嘤
